name: shortnews
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  screenshot: ^2.3.0
  # geocoding: ^2.2.0
  # location: ^6.0.1
  
  cached_network_image: ^3.3.1  
  responsive_sizer: ^3.3.0+1
  fading_widget_animation: ^0.0.1
  provider: ^6.1.1
  internet_connection_checker: ^1.0.0+1
  translator: ^1.0.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  flutter_localization: ^0.2.0
  card_swiper: ^3.0.1
  flutter_advanced_drawer: ^1.3.5
  # firebase dependency 
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_dynamic_links: ^5.5.4
  firebase_messaging: ^14.9.1
  # ads
  # State Mangement Libarary
  get: ^4.6.1
  package_info:  
  page_transition: ^2.1.0
  url_launcher: ^6.2.5
  animated_switch: ^0.0.3
  video_player: ^2.8.3
  flick_video_player: ^0.7.0
  flutter_switch: ^0.3.2
  firebase_auth: ^4.17.9
  fluttertoast: ^8.2.4
  firebase_remote_config: ^4.3.18
  # Notifications
  flutter_ringtone_player: ^3.2.0
  in_app_notification: ^1.1.2
  hexcolor: ^3.0.1
  flutter_local_notifications: ^17.1.0
  awesome_notifications: any
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  share_plus: 
  cupertino_icons: ^1.0.6
  pdf: ^3.10.8
  open_file: ^3.3.2
  dropdown_button2: ^2.3.9
  image_picker: ^0.8.5+3
  file_picker:
  firebase_storage: ^11.7.1
  firebase_app_check: ^0.2.2+5
  pin_code_fields: ^8.0.1
  top_modal_sheet: ^2.1.0
  photo_view: ^0.15.0
  vimeo_video_player: ^0.0.15
  chewie: ^1.3.1
  change_app_package_name: ^1.1.0
  flutter_tts: ^3.3.0
  timeago: ^3.7.0
  app_settings: ^5.1.1
  skeletonizer: ^1.4.1+1
  skeleton_loader: ^2.0.0+4
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.1.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true

  assets:
   
    - assets/images/
    - assets/sound/
   


